Repository SOPT-all/SOPT-all-35-APPJAM-ANDROID-ACON, pull requests merged in 2025-01, with the labels that each got.

#20 [Feat] readme 내용 작성
  README.md
Labels: DOCS📜, 🐸성민🐸

#21 [Mod] readme 수정
  README.md
Labels: MOD✅, 🐸성민🐸

#19 [Feat/#10] Coroutine Hilt module 추가
  app/src/main/java/com/acon/acon/di/CoroutineDispatchersModule.kt
  app/src/main/java/com/acon/acon/di/CoroutineScopesModule.kt
  core/common/build.gradle.kts
  core/common/src/androidTest/java/com/acon/core/common/ExampleInstrumentedTest.kt
  core/common/src/main/AndroidManifest.xml
  core/common/src/main/java/com/acon/core/common/DispatcherQualifiers.kt
  core/common/src/main/java/com/acon/core/common/MyClass.kt
  core/common/src/test/java/com/acon/core/common/ExampleUnitTest.kt
  feature/home/build.gradle.kts
  settings.gradle.kts
Labels: INIT, ☀️상일☀️

#28 [Feat/#26] snackbar component
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/acon/core/designsystem/component/snackbar/AconSnackBar.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/snackbar/AconTextSnackBar.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/snackbar/AconTextSnackBarWithButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/theme/Color.kt
  gradle/libs.versions.toml
Labels: ⭐세영⭐, FEATURE✨

#27 [Feat/#24] 라디오버튼, 칩 컴포넌트
  core/designsystem/src/main/java/com/acon/core/designsystem/component/chip/AconChip.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/radiobutton/AconRadioButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/theme/Type.kt
Labels: ☀️상일☀️, FEATURE✨

#33 [Feat/#14] 공통 컴포넌트 구현 (버튼)
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconFilledLargeButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconFilledMediumButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconGoogleLoginButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconOutlinedLargeButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconOutlinedMediumButton.kt
  core/designsystem/src/main/res/values/strings.xml
Labels: UI✨, 🐸성민🐸

#36 [Feat/#31] 지도 API 모듈화
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  core/map/.gitignore
  core/map/build.gradle.kts
  core/map/consumer-rules.pro
  core/map/proguard-rules.pro
  core/map/src/androidTest/java/com/acon/core/map/ExampleInstrumentedTest.kt
  core/map/src/main/AndroidManifest.xml
  core/map/src/main/java/com/acon/core/map/MapUtils.kt
  core/map/src/test/java/com/acon/core/map/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: INIT, ☀️상일☀️, FEATURE✨

#37 [Feat/#12] 에러 핸들링 아키텍처
  app/src/main/AndroidManifest.xml
  core/utils/feature/build.gradle.kts
  core/utils/feature/src/main/java/com/acon/core/utils/feature/base/BaseContainerHost.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/acon/data/di/NetworkModule.kt
  data/src/main/kotlin/com/acon/data/error/ErrorUtils.kt
  data/src/main/kotlin/com/acon/data/error/NetworkErrorResponse.kt
  data/src/main/kotlin/com/acon/data/error/RemoteError.kt
  domain/build.gradle.kts
  domain/src/main/java/com/acon/domain/MyClass.kt
  domain/src/main/java/com/acon/domain/error/RootError.kt
  gradle/libs.versions.toml
Labels: INIT, ☀️상일☀️

#38 [Feat/#34] 공통 컴포넌트 구현 (다이얼로그)
  core/designsystem/src/main/java/com/acon/core/designsystem/component/dialog/AconDialog.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/dialog/AconOneButtonDialog.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/dialog/AconTwoButtonDialog.kt
Labels: UI✨, 🐸성민🐸

#42 [Fix/#41] 네비게이션 버그 수정
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/AreaVerificationNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/OnboardingNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SignInNavigation.kt
  app/src/main/java/com/acon/acon/navigation/route/AreaVerificationRoute.kt
  app/src/main/java/com/acon/acon/navigation/route/OnboardingRoute.kt
  app/src/main/java/com/acon/acon/navigation/route/SignInRoute.kt
Labels: ☀️상일☀️, FIX🔨

#43 [Feat#40] 피그마 graphics 이미지 추가
  core/designsystem/src/main/res/drawable/ic_construction_160.xml
  core/designsystem/src/main/res/drawable/ic_error_1_120.xml
  core/designsystem/src/main/res/drawable/ic_error_1_80.xml
  core/designsystem/src/main/res/drawable/ic_error_2_120.xml
  core/designsystem/src/main/res/drawable/ic_error_2_80.xml
  core/designsystem/src/main/res/drawable/ic_local_acon_24.xml
  core/designsystem/src/main/res/drawable/ic_local_acon_80.xml
  core/designsystem/src/main/res/drawable/ic_locationn_now_44.xml
  core/designsystem/src/main/res/drawable/ic_normal_acon_80.xml
  core/designsystem/src/main/res/drawable/ic_symbol_logo_org_160.xml
  core/designsystem/src/main/res/drawable/ic_symbol_logo_white_160.xml
  core/designsystem/src/main/res/drawable/ic_visitor_acon_24.xml
  core/designsystem/src/main/res/drawable/ic_word_logo_splash_org_78.xml
  core/designsystem/src/main/res/drawable/ic_word_logo_splash_white_78.xml
  core/designsystem/src/main/res/drawable/img_save_154.xml
  core/designsystem/src/main/res/drawable/img_upload_finish_320.xml
Labels: UI✨, 🐸성민🐸

#48 [Feat/#39] 로그인 화면 UI 구현
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconGoogleLoginButton.kt
  feature/signin/.gitignore
  feature/signin/build.gradle.kts
  feature/signin/consumer-rules.pro
  feature/signin/proguard-rules.pro
  feature/signin/src/androidTest/java/com/acon/feature/signin/ExampleInstrumentedTest.kt
  feature/signin/src/main/AndroidManifest.xml
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInScreen.kt
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInScreenContent.kt
  feature/signin/src/main/res/values/strings.xml
  feature/signin/src/test/java/com/acon/feature/signin/ExampleUnitTest.kt
  settings.gradle.kts
Labels: FEATURE✨, 🐸성민🐸

#50 [Feat/#46] 장소탐색 로딩 화면
  core/designsystem/src/main/java/com/acon/core/designsystem/animation/Skeleton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/loading/SkeletonItem.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotItem.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
Labels: UI✨, ☀️상일☀️, FEATURE✨

#53 [Feat/#15] location permission
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/MainActivity.kt
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/AreaVerificationNavigation.kt
  app/src/main/java/com/acon/acon/navigation/route/AreaVerificationRoute.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconFilledLargeButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/dialog/AconOneButtonDialog.kt
  core/map/src/main/java/com/acon/core/map/MapUtils.kt
  feature/areaverification/.gitignore
  feature/areaverification/build.gradle.kts
  feature/areaverification/src/androidTest/java/com/acon/feature/AreaVerification/ExampleInstrumentedTest.kt
  feature/areaverification/src/main/AndroidManifest.xml
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/AreaVerificationScreenContainer.kt
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/AreaVerificationSideEffect.kt
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/AreaVerificationState.kt
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/AreaVerificationViewModel.kt
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/LocationMapScreen.kt
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/PreferenceMapScreen.kt
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/component/AreaVerificationButton.kt
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/component/DottoriSelectionBottomSheet.kt
  feature/areaverification/src/main/res/drawable/ic_local_acon.xml
  feature/areaverification/src/main/res/drawable/ic_normal_acon.xml
  feature/areaverification/src/main/res/values/strings.xml
  feature/areaverification/src/test/java/com/acon/feature/AreaVerification/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: UI✨, ⭐세영⭐

#56 [Feat/#44] onboarding 첫 번재, 두 번째 UI 구현
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/navigation/nested/OnboardingNavigation.kt
  app/src/main/java/com/acon/acon/navigation/route/OnboardingRoute.kt
  feature/onboarding/.gitignore
  feature/onboarding/build.gradle.kts
  feature/onboarding/consumer-rules.pro
  feature/onboarding/proguard-rules.pro
  feature/onboarding/src/androidTest/java/com/acon/feature/onboarding/ExampleInstrumentedTest.kt
  feature/onboarding/src/main/AndroidManifest.xml
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/FoodGrid.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/OnboardingProgressIndicator.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/OnboardingTopBar.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/PreferFoodTypeSelectGrid.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/SkipButton.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredFoodRateScreen/PreferredFoodRateScreenViewModel.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredFoodRateScreen/composable/PreferredFoodRateScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredFoodRateScreen/composable/PreferredFoodRateScreenContainer.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/UnlikeFoodSelectScreen/UnlikeFoodSelectScreenViewModel.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/UnlikeFoodSelectScreen/composable/UnlikeFoodSelectScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/UnlikeFoodSelectScreen/composable/UnlikeFoodSelectScreenContainer.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/type/FoodItems.kt
  feature/onboarding/src/main/res/drawable/food_american.png
  feature/onboarding/src/main/res/drawable/food_asian.png
  feature/onboarding/src/main/res/drawable/food_chinese.png
  feature/onboarding/src/main/res/drawable/food_img_1.png
  feature/onboarding/src/main/res/drawable/food_img_2.png
  feature/onboarding/src/main/res/drawable/food_img_3.png
  feature/onboarding/src/main/res/drawable/food_img_4.png
  feature/onboarding/src/main/res/drawable/food_img_5.png
  feature/onboarding/src/main/res/drawable/food_japanese.png
  feature/onboarding/src/main/res/drawable/food_korean.png
  feature/onboarding/src/main/res/drawable/food_street.png
  feature/onboarding/src/main/res/drawable/ic_1.xml
  feature/onboarding/src/main/res/drawable/ic_2.xml
  feature/onboarding/src/main/res/drawable/ic_3.xml
  feature/onboarding/src/main/res/drawable/ic_4.xml
  feature/onboarding/src/main/res/mipmap-anydpi-v26/food_img_1.xml
  feature/onboarding/src/main/res/mipmap-anydpi-v26/food_img_1_round.xml
  feature/onboarding/src/main/res/mipmap-hdpi/food_img_1.webp
  feature/onboarding/src/main/res/mipmap-hdpi/food_img_1_foreground.webp
  feature/onboarding/src/main/res/mipmap-hdpi/food_img_1_round.webp
  feature/onboarding/src/main/res/mipmap-mdpi/food_img_1.webp
  feature/onboarding/src/main/res/mipmap-mdpi/food_img_1_foreground.webp
  feature/onboarding/src/main/res/mipmap-mdpi/food_img_1_round.webp
  feature/onboarding/src/main/res/mipmap-xhdpi/food_img_1.webp
  feature/onboarding/src/main/res/mipmap-xhdpi/food_img_1_foreground.webp
  feature/onboarding/src/main/res/mipmap-xhdpi/food_img_1_round.webp
  feature/onboarding/src/main/res/mipmap-xxhdpi/food_img_1.webp
  feature/onboarding/src/main/res/mipmap-xxhdpi/food_img_1_foreground.webp
  feature/onboarding/src/main/res/mipmap-xxhdpi/food_img_1_round.webp
  feature/onboarding/src/main/res/mipmap-xxxhdpi/food_img_1.webp
  feature/onboarding/src/main/res/mipmap-xxxhdpi/food_img_1_foreground.webp
  feature/onboarding/src/main/res/mipmap-xxxhdpi/food_img_1_round.webp
  feature/onboarding/src/test/java/com/acon/feature/onboarding/ExampleUnitTest.kt
  gradle/libs.versions.toml
Labels: UI✨, ⛄지원⛄

#58 [Feat/#55] 바텀 네비게이션
  app/src/main/java/com/acon/acon/MainActivity.kt
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/bottom/BottomBar.kt
  app/src/main/java/com/acon/acon/navigation/bottom/BottomNavType.kt
  app/src/main/java/com/acon/acon/navigation/nested/SpotNavigation.kt
  app/src/main/res/values/strings.xml
  core/designsystem/src/main/java/com/acon/core/designsystem/ComposeExtensions.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/animation/ScreenTransition.kt
Labels: UI✨, ☀️상일☀️, FEATURE✨

#68 [Docs] Update issue_template.md
  .github/ISSUE_TEMPLATE/issue_template.md
Labels: DOCS📜, 🐸성민🐸

#59 [Feat/#47] upload acon count
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/UploadNavigation.kt
  app/src/main/java/com/acon/acon/navigation/route/UploadRoute.kt
  core/map/src/main/AndroidManifest.xml
  core/map/src/main/java/com/acon/core/map/MapUtils.kt
  feature/onboarding/src/main/res/mipmap-anydpi-v26/food_img_1.xml
  feature/onboarding/src/main/res/mipmap-anydpi-v26/food_img_1_round.xml
  feature/upload/.gitignore
  feature/upload/build.gradle.kts
  feature/upload/consumer-rules.pro
  feature/upload/proguard-rules.pro
  feature/upload/src/androidTest/java/com/acon/feature/upload/ExampleInstrumentedTest.kt
  feature/upload/src/main/AndroidManifest.xml
  feature/upload/src/main/java/com/acon/feature/upload/UploadContainer.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadIntent.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadSideEffect.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadState.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadSuccessContainer.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadViewModel.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/DotoriIndicator.kt
  feature/upload/src/main/res/drawable/img_upload_finish.xml
  feature/upload/src/main/res/raw/dotori1.json
  feature/upload/src/main/res/raw/dotori2.json
  feature/upload/src/main/res/raw/dotori3.json
  feature/upload/src/main/res/raw/dotori4.json
  feature/upload/src/main/res/raw/dotori5.json
  feature/upload/src/test/java/com/acon/feature/upload/ExampleUnitTest.kt
  gradle/libs.versions.toml
  settings.gradle.kts
Labels: UI✨, ⭐세영⭐, FEATURE✨

#61 [Feat/#60] onboarding 3 UI
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/navigation/nested/OnboardingNavigation.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/FreqPlaceSelectGrid.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/FrequentPlaceSelectScreen/FrequentPlaceSelectScreenViewModel.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/FrequentPlaceSelectScreen/composable/FrequentPlaceSelectScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/FrequentPlaceSelectScreen/composable/FrequentPlaceSelectScreenContainer.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredFoodRateScreen/composable/PreferredFoodRateScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredFoodRateScreen/composable/PreferredFoodRateScreenContainer.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/type/PlaceItems.kt
  feature/onboarding/src/main/res/drawable/place_img_1.png
  feature/onboarding/src/main/res/drawable/place_img_2.png
  feature/onboarding/src/main/res/drawable/place_img_3.png
  feature/onboarding/src/main/res/drawable/place_img_4.png
  settings.gradle.kts
Labels: UI✨, FEATURE✨, ⛄지원⛄

#64 [Feat/#62] onboarding 4번째 화면 UI 구현
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/navigation/nested/OnboardingNavigation.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/FreqPlaceSelectGrid.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredPlaceSelectScreen/PreferredPlaceSelectViewModel.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredPlaceSelectScreen/composable/PreferredPlaceSelectScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredPlaceSelectScreen/composable/PreferredPlaceSelectScreenContainer.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/type/PlaceItems.kt
Labels: UI✨, FEATURE✨, ⛄지원⛄

#63 [Feat/#49] 구글로그인 구현
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/MainActivity.kt
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SignInNavigation.kt
  core/common/src/main/java/com/acon/core/common/AuthQualifiers.kt
  data/build.gradle.kts
  data/src/main/kotlin/com/acon/data/api/remote/AuthApi.kt
  data/src/main/kotlin/com/acon/data/api/remote/ReissueTokenApi.kt
  data/src/main/kotlin/com/acon/data/datasource/local/TokenLocalDataSource.kt
  data/src/main/kotlin/com/acon/data/datasource/remote/AuthRemoteDataSource.kt
  data/src/main/kotlin/com/acon/data/datasource/remote/TokenRemoteDataSource.kt
  data/src/main/kotlin/com/acon/data/di/ApiModule.kt
  data/src/main/kotlin/com/acon/data/di/AuthAuthenticator.kt
  data/src/main/kotlin/com/acon/data/di/GoogleTokenRepositoryModule.kt
  data/src/main/kotlin/com/acon/data/di/NetworkModule.kt
  data/src/main/kotlin/com/acon/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/acon/data/dto/request/GoogleTokenRequest.kt
  data/src/main/kotlin/com/acon/data/dto/request/RefreshRequest.kt
  data/src/main/kotlin/com/acon/data/dto/response/GoogleTokenResponse.kt
  data/src/main/kotlin/com/acon/data/dto/response/RefreshResponse.kt
  data/src/main/kotlin/com/acon/data/repository/AuthRepositoryImpl.kt
  data/src/main/kotlin/com/acon/data/repository/GoogleTokenRepositoryImpl.kt
  domain/src/main/java/com/acon/domain/error/auth/PostLoginError.kt
  domain/src/main/java/com/acon/domain/model/auth/RefreshToken.kt
  domain/src/main/java/com/acon/domain/repository/AuthRepository.kt
  domain/src/main/java/com/acon/domain/repository/GoogleTokenRepository.kt
  domain/src/main/java/com/acon/domain/type/SocialType.kt
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInScreen.kt
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInScreenContent.kt
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInViewModel.kt
  feature/signin/src/main/java/com/acon/feature/signin/screen/component/SignInTopBar.kt
  feature/signin/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: FEATURE✨, 🐸성민🐸

#74 [Feat/#69] SpotDetailView UI 구현
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/ComposeExtensions.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/theme/Color.kt
  core/designsystem/src/main/res/drawable/ic_no_store_image_80.xml
  core/designsystem/src/main/res/drawable/ic_store_detail_menu_78.xml
  domain/src/main/java/com/acon/domain/model/spot/Menu.kt
  domain/src/main/java/com/acon/domain/model/spot/SpotDetailInfo.kt
  feature/spot/build.gradle.kts
  feature/spot/src/main/java/com/acon/feature/spot/PriceExtensions.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/SpotDetailViewModel.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/SpotDetailScreen.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/SpotDetailScreenContainer.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/MenuItem.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/MoveToTopFAB.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/RestaurantBottomActionBar.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/SpotChip.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/SpotDetailTabPager.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/SpotDetailTopBar.kt
  gradle/libs.versions.toml
Labels: UI✨, FEATURE✨, 🐸성민🐸

#71 [Feat/#57] 장소 탐색 필터링 및 Glassmorphism
  app/src/main/java/com/acon/acon/MainActivity.kt
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/acon/core/designsystem/blur/BlurUtils.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/chip/AconChip.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/chip/AconChipFlowRow.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/slider/AconSlider.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/theme/Color.kt
  core/designsystem/src/main/res/values/strings.xml
  domain/src/main/java/com/acon/domain/model/spot/SpotListRequest.kt
  domain/src/main/java/com/acon/domain/type/OptionType.kt
  domain/src/main/java/com/acon/domain/type/SpotType.kt
  feature/spot/build.gradle.kts
  feature/spot/src/main/java/com/acon/feature/spot/TypeExtensions.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotItem.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreenContainer.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/bottomsheet/CafeBottomSheetContent.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/bottomsheet/RestaurantBottomSheetContent.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/bottomsheet/SpotFilterBottomSheet.kt
  feature/spot/src/main/java/com/acon/feature/spot/type/AvailableWalkingTimeType.kt
  feature/spot/src/main/java/com/acon/feature/spot/type/CafePriceRangeType.kt
  feature/spot/src/main/java/com/acon/feature/spot/type/FloatingButtonType.kt
  feature/spot/src/main/java/com/acon/feature/spot/type/RestaurantPriceRangeType.kt
  feature/spot/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: UI✨, ☀️상일☀️, FEATURE✨

#72 [Feat/#52] 위치 권한 요청 다이얼로그
  core/utils/feature/build.gradle.kts
  core/utils/feature/src/main/java/com/acon/core/utils/feature/permission/LocationPermission.kt
  core/utils/feature/src/main/java/com/acon/core/utils/feature/permission/PermissionDialog.kt
  core/utils/feature/src/main/res/values/strings.xml
Labels: ☀️상일☀️, FEATURE✨

#77 [Feat/#76] 바텀 네비게이션 바 글라스모피즘
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/blur/BlurUtils.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreenContainer.kt
Labels: UI✨, ☀️상일☀️, FEATURE✨

#79 [Feat/#75] 장소 상세 화면 글래스모피즘 적용, orbit 적용, 네이버 지도 연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SpotNavigation.kt
  app/src/main/res/xml/network_security_config.xml
  core/designsystem/src/main/res/drawable/ic_arrow_left_24.xml
  core/designsystem/src/main/res/drawable/ic_arrow_left_28.xml
  core/designsystem/src/main/res/drawable/ic_arrow_up_24.xml
  core/designsystem/src/main/res/drawable/ic_arrow_up_30.xml
  core/designsystem/src/main/res/drawable/ic_local_acon_24.xml
  core/designsystem/src/main/res/drawable/ic_local_acon_28.xml
  core/designsystem/src/main/res/drawable/ic_location_gray_16.xml
  core/designsystem/src/main/res/drawable/ic_location_gray_20.xml
  core/designsystem/src/main/res/drawable/ic_visitor_acon_24.xml
  core/designsystem/src/main/res/drawable/ic_visitor_acon_28.xml
  data/src/main/kotlin/com/acon/data/api/remote/SpotApi.kt
  data/src/main/kotlin/com/acon/data/datasource/remote/SpotRemoteDataSource.kt
  data/src/main/kotlin/com/acon/data/dto/response/SpotDetailInfoResponse.kt
  data/src/main/kotlin/com/acon/data/dto/response/SpotDetailMenuResponse.kt
  data/src/main/kotlin/com/acon/data/repository/SpotRepositoryImpl.kt
  domain/src/main/java/com/acon/domain/error/spot/GetSpotDetailInfoError.kt
  domain/src/main/java/com/acon/domain/error/spot/GetSpotMenuListError.kt
  domain/src/main/java/com/acon/domain/model/spot/SpotDetailInfo.kt
  domain/src/main/java/com/acon/domain/model/spot/SpotDetailMenu.kt
  domain/src/main/java/com/acon/domain/repository/SpotRepository.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/OnboardingTopBar.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/SpotDetailViewModel.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/SpotDetailScreen.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/SpotDetailScreenContainer.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/MenuItem.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/MoveToTopFAB.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/RestaurantBottomActionBar.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/SpotChip.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/SpotDetailTabPager.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/SpotDetailTopBar.kt
  feature/spot/src/main/java/openNaverMap.kt
  feature/spot/src/main/res/values/strings.xml
Labels: FEATURE✨, 🐸성민🐸

#78 [Feat/#70] upload location
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/UploadNavigation.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/acon/core/designsystem/blur/BlurUtils.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/button/AconFilledLargeButton.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/topbar/AconTopBar.kt
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/AreaVerificationScreenContainer.kt
  feature/upload/build.gradle.kts
  feature/upload/src/main/java/com/acon/feature/upload/LocationItem.kt
  feature/upload/src/main/java/com/acon/feature/upload/MockSpotData.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadContainer.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadIntent.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadState.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadStep.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadSuccessContainer.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadViewModel.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/AconSearchTextField.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/DotoriIndicator.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/LocationItem.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/LocationSearchBottomSheet.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/LocationSelectionButton.kt
  feature/upload/src/main/res/drawable/and_ic_add_20.xml
  feature/upload/src/main/res/drawable/and_ic_location_gray_28.xml
  feature/upload/src/main/res/drawable/ic_dissmiss_circle_gray.xml
  feature/upload/src/main/res/drawable/ic_no_location.xml
  feature/upload/src/main/res/raw/dotori1.json
  feature/upload/src/main/res/raw/dotori2.json
  feature/upload/src/main/res/raw/dotori3.json
  feature/upload/src/main/res/raw/dotori4.json
  feature/upload/src/main/res/raw/dotori5.json
  gradle/libs.versions.toml
Labels: UI✨, ⭐세영⭐, FEATURE✨

#85 [Feature] Base URL 세팅
  data/build.gradle.kts
  data/src/main/AndroidManifest.xml
  data/src/main/kotlin/com/acon/data/di/NetworkModule.kt
Labels: INIT, ☀️상일☀️

#81 [Feat/#73] 장소 탐색 UI 디테일
  .gitignore
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/chip/AconChip.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/slider/AconSlider.kt
  core/utils/feature/src/main/java/com/acon/core/utils/feature/permission/LocationPermission.kt
  data/src/main/kotlin/com/acon/data/dto/request/SpotListRequest.kt
  data/src/main/kotlin/com/acon/data/repository/SpotRepositoryImpl.kt
  domain/src/main/java/com/acon/domain/model/spot/SpotListRequest.kt
  domain/src/main/java/com/acon/domain/repository/SpotRepository.kt
  domain/src/main/java/com/acon/domain/type/OptionType.kt
  feature/spot/build.gradle.kts
  feature/spot/src/main/java/com/acon/feature/spot/TypeExtensions.kt
  feature/spot/src/main/java/com/acon/feature/spot/mock/SpotListMock.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotItem.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListPullToRefreshIndicator.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreenContainer.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/bottomsheet/CafeBottomSheetContent.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/bottomsheet/RestaurantBottomSheetContent.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/bottomsheet/SpotFilterBottomSheet.kt
  feature/spot/src/main/java/com/acon/feature/spot/state/ConditionState.kt
  feature/spot/src/main/java/com/acon/feature/spot/type/SpotShowType.kt
  feature/spot/src/main/res/raw/lottie_progress_w.json
  feature/spot/src/main/res/values/strings.xml
Labels: MOD✅, UI✨, ☀️상일☀️, FEATURE✨, ADD➕

#86 [Mod/#83] 네비게이션 구조 수정
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/AreaVerificationNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/OnboardingNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SignInNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SpotNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/UploadNavigation.kt
  feature/areaverification/build.gradle.kts
  feature/areaverification/src/main/java/com/acon/feature/AreaVerification/AreaVerificationRoute.kt
  feature/onboarding/build.gradle.kts
  feature/onboarding/src/main/java/com/acon/feature/onboarding/OnboardingRoute.kt
  feature/signin/build.gradle.kts
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInRoute.kt
  feature/spot/build.gradle.kts
  feature/spot/src/main/java/com/acon/feature/spot/SpotRoute.kt
  feature/upload/build.gradle.kts
  feature/upload/src/main/java/com/acon/feature/upload/UploadRoute.kt
Labels: MOD✅, ☀️상일☀️

#90 Mod/#89 apply noripple
  app/build.gradle.kts
  core/designsystem/src/main/java/com/acon/core/designsystem/ComposeExtensions.kt
  data/build.gradle.kts
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/FoodGrid.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/FreqPlaceSelectGrid.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/PreferFoodTypeSelectGrid.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/component/PreferPlaceTypeSelectGrid.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/FrequentPlaceSelectScreen/composable/FrequentPlaceSelectScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PerferredPlaceRateScreen/composable/PerferredPlaceRateScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredFoodRateScreen/composable/PreferredFoodRateScreenContainer.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredPlaceSelectScreen/composable/PreferredPlaceSelectScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/UnlikeFoodSelectScreen/composable/UnlikeFoodSelectScreenContainer.kt
Labels: MOD✅, FIX🔨, ⛄지원⛄

#91 [Fix/#88] 색상, 아이콘 수정
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/bottom/BottomBar.kt
  core/designsystem/src/main/res/drawable/ic_dissmiss_28.xml
  core/designsystem/src/main/res/drawable/ic_filter_w_28.xml
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreenContainer.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/bottomsheet/SpotFilterBottomSheet.kt
  feature/spot/src/main/java/com/acon/feature/spot/type/FloatingButtonType.kt
Labels: UI✨, ☀️상일☀️, FIX🔨

#98 [Fix/#97] 온보딩 중간에 skip 시 바로 SpotListView로 이동하도록 수정
  app/src/main/java/com/acon/acon/navigation/nested/OnboardingNavigation.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/FrequentPlaceSelectScreen/composable/FrequentPlaceSelectScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PerferredPlaceRateScreen/composable/PerferredPlaceRateScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredFoodRateScreen/composable/PreferredFoodRateScreenContainer.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/PreferredPlaceSelectScreen/composable/PreferredPlaceSelectScreen.kt
  feature/onboarding/src/main/java/com/acon/feature/onboarding/screen/UnlikeFoodSelectScreen/composable/UnlikeFoodSelectScreenContainer.kt
Labels: MOD✅, ⛄지원⛄

#99 [Feat/#80] 로그인 orbit 적용, 스플래시 추가
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SignInNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/SplashNavigation.kt
  app/src/main/java/com/acon/acon/navigation/route/SplashRoute.kt
  core/designsystem/src/main/res/drawable/ic_word_logo_splash_org_78.xml
  core/designsystem/src/main/res/drawable/ic_word_logo_splash_org_91.xml
  data/src/main/kotlin/com/acon/data/datasource/local/TokenLocalDataSource.kt
  data/src/main/kotlin/com/acon/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/acon/data/dto/response/SpotDetailMenuResponse.kt
  data/src/main/kotlin/com/acon/data/repository/SpotRepositoryImpl.kt
  data/src/main/kotlin/com/acon/data/repository/TokenRepositoryImpl.kt
  domain/src/main/java/com/acon/domain/repository/TokenRepository.kt
  feature/signin/build.gradle.kts
  feature/signin/src/main/AndroidManifest.xml
  feature/signin/src/main/assets/acon_splash_lottie.json
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInScreen.kt
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInScreenContent.kt
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInViewModel.kt
  feature/signin/src/main/java/com/acon/feature/signin/screen/component/SignInTopBar.kt
  feature/signin/src/main/java/com/acon/feature/signin/splash/SplashScreen.kt
  feature/signin/src/main/java/com/acon/feature/signin/splash/SplashScreenContent.kt
  feature/signin/src/main/java/com/acon/feature/signin/splash/SplashViewModel.kt
  feature/signin/src/main/res/values/strings.xml
  feature/spot/src/main/java/com/acon/feature/spot/PriceExtensions.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/SpotDetailViewModel.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/SpotDetailScreen.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/MenuItem.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/RestaurantBottomActionBar.kt
  gradle/libs.versions.toml
Labels: FEATURE✨, 🐸성민🐸

#102 [Fix/#101] 스크롤 영역 수정
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/blur/BlurUtils.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotItem.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
Labels: ☀️상일☀️, FIX🔨

#113 [Feat/#111]: Update dotori count lottie
  feature/areaverification/src/main/java/com/acon/feature/areaverification/LocationMapScreen.kt
  feature/upload/src/main/res/raw/dotori2.json
  feature/upload/src/main/res/raw/dotori3.json
  feature/upload/src/main/res/raw/dotori4.json
  feature/upload/src/main/res/raw/dotori5.json
Labels: UI✨, ⭐세영⭐

#107 [Fix/#104] 동네 API, 프로필 빈 화면
  app/build.gradle.kts
  app/src/main/java/com/acon/acon/navigation/AconNavigation.kt
  app/src/main/java/com/acon/acon/navigation/nested/ProfileNavigation.kt
  core/common/src/main/java/com/acon/core/common/AuthQualifiers.kt
  core/designsystem/src/main/res/drawable/ic_map_w_28.xml
  core/designsystem/src/main/res/drawable/ic_my_g_location_28.xml
  data/build.gradle.kts
  data/src/main/kotlin/com/acon/data/api/remote/MapApi.kt
  data/src/main/kotlin/com/acon/data/datasource/remote/MapRemoteDataSource.kt
  data/src/main/kotlin/com/acon/data/di/ApiModule.kt
  data/src/main/kotlin/com/acon/data/di/NetworkModule.kt
  data/src/main/kotlin/com/acon/data/di/RepositoryModule.kt
  data/src/main/kotlin/com/acon/data/dto/response/GeocodingResponse.kt
  data/src/main/kotlin/com/acon/data/repository/MapRepositoryImpl.kt
  domain/src/main/java/com/acon/domain/model/map/ReverseGeocoding.kt
  domain/src/main/java/com/acon/domain/repository/MapRepository.kt
  feature/profile/.gitignore
  feature/profile/build.gradle.kts
  feature/profile/consumer-rules.pro
  feature/profile/proguard-rules.pro
  feature/profile/src/androidTest/java/com/acon/feature/profile/ExampleInstrumentedTest.kt
  feature/profile/src/main/AndroidManifest.xml
  feature/profile/src/main/java/com/acon/feature/profile/ProfileRoute.kt
  feature/profile/src/main/java/com/acon/feature/profile/screen/profile/composable/ProfileScreen.kt
  feature/profile/src/main/java/com/acon/feature/profile/screen/profile/composable/ProfileScreenContainer.kt
  feature/profile/src/main/res/values/strings.xml
  feature/profile/src/test/java/com/acon/feature/profile/ExampleUnitTest.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/SpotListViewModel.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotlist/composable/SpotListScreen.kt
  feature/spot/src/main/java/com/acon/feature/spot/type/FloatingButtonType.kt
  settings.gradle.kts
Labels: ☀️상일☀️, FIX🔨, FEATURE✨

#108 [Feature/#100] 최근 길 안내 저장 API 연동, SpotDetailView UI 요소 추가, 추정
  data/src/main/kotlin/com/acon/data/api/remote/SpotApi.kt
  data/src/main/kotlin/com/acon/data/datasource/remote/SpotRemoteDataSource.kt
  data/src/main/kotlin/com/acon/data/di/ApiModule.kt
  data/src/main/kotlin/com/acon/data/dto/request/RecentNavigationLocationRequest.kt
  data/src/main/kotlin/com/acon/data/repository/SpotRepositoryImpl.kt
  domain/src/main/java/com/acon/domain/error/spot/FetchRecentNavigationLocationError.kt
  domain/src/main/java/com/acon/domain/repository/SpotRepository.kt
  feature/signin/src/main/assets/acon_splash_lottie.json
  feature/signin/src/main/java/com/acon/feature/signin/screen/SignInScreenContent.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/SpotDetailViewModel.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/SpotDetailScreen.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/SpotDetailScreenContainer.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/MoveToTopFAB.kt
  feature/spot/src/main/java/com/acon/feature/spot/screen/spotdetail/composable/component/SpotChip.kt
  feature/spot/src/main/res/values/strings.xml
Labels: FEATURE✨, 🐸성민🐸

#115 [Feat/#114] 2nd-QA
  core/designsystem/src/main/java/com/acon/core/designsystem/component/dialog/AconDialog.kt
  core/designsystem/src/main/java/com/acon/core/designsystem/component/dialog/AconTwoButtonDialog.kt
  feature/areaverification/src/main/java/com/acon/feature/areaverification/component/DottoriSelectionBottomSheet.kt
  feature/areaverification/src/main/res/drawable/ic_mark_48.xml
  feature/upload/src/main/java/com/acon/feature/upload/UploadContainer.kt
  feature/upload/src/main/java/com/acon/feature/upload/UploadSuccessContainer.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/AconSearchTextField.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/LocationItem.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/LocationSearchBottomSheet.kt
  feature/upload/src/main/java/com/acon/feature/upload/component/LocationSelectionButton.kt
Labels: UI✨, ⭐세영⭐, FIX🔨
